### ISSUE TITLE
hiding sharing counts by default

### ISSUE THREAD

**Issue by ssstofff** [panzi/SocialSharePrivacy#69]
how to hide sharing counts by default ?

It could be done via CSS, hiding per media, but would prefer to cut the counter even before it counts (preserves also bandwidth)

**Comment by panzi** [comment]
Do you mean the count bubbles after you enable a button? If you don't want to have this, why use this script at all and not just use a static link?

**Comment by ssstofff** [comment]
That's true! Stupid me.

**Comment by Anke** [comment]
Why not just use a static link instead of your script? The great thing about your script is that it offers more social media buttons than others! Yet, I'd also prefer buttons only without counters, but no static links as they would protect a user's privacy. So, there is no option to disable the counting?

**Comment by panzi** [comment]
Currently there is no option for that because I don't really see the use.
